name: Deploy a GitHub Pages

on:
  push:
    branches: ["main"] # O la rama que uses como principal

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/checkout@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build

      - name: Fix para Jekyll (.nojekyll)
        run: touch dist/.nojekyll

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4